version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: helpdesk_postgres
    restart: always
    environment:
      POSTGRES_DB: helpdeskIncident
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
