server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: helpdesk
  flyway:
    enable: true
    baseline-on-migrate: false
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    #    username: postgres #Aqui ou no .env - necessário dependência paulswharz
    #    password: admin123
    #    url: jdbc:postgresql://localhost:5432/helpdeskIncident
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}
    url: ${env.DATABASE_URL}
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html # Defina explicitamente o caminho do Swagger UI
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allow-credentials: true

#Variáveis da minha aplicação
#Em qual local do seu computador serão salvos os arquivos dos anexos enviados
helpdesk:
  attachments-folder: ${env.ATTACHMENT_FOLDER}

jwt:
  secret: h9G+QWz3G7u0Rk5+Q3YzN9Kz+zN5R3F5zYQw3zN6Q1Z3Qk5yW3L0==
